### ISSUE TITLE
Django 1.8 support

### ISSUE THREAD

**Issue by GertBurger** [dimagi/django-prbac#12]
Hi

Has anyone started looking into this?

**Comment by czue** [comment]
not at the moment. we maintain this library as a part of https://github.com/dimagi/commcare-hq and likely won't support django 1.8 until we upgrade that repository

**Comment by czue** [comment]
in the meantime we would welcome any pull requests adding it though!

**Comment by lseelenbinder** [comment]
Are there any updates in regards to this? I'm currently using @GertBurger's feature branch, but would like to get back to standard as soon as possible.

**Comment by emord** [comment]
@lseelenbinder that was merged yesterday https://github.com/dimagi/django-prbac/pull/13

**Comment by lseelenbinder** [comment]
@emord Fantastic.
