### ISSUE TITLE
Grant.objects.get doesn't honor the assignment parameter

### ISSUE THREAD

**Issue by MCGallaspy** [dimagi/django-prbac#19]
Hiya! Like this module, even though there doesn't seem to be any active development. I noticed the following error:

```python
from django_prbac.models import Role, Grant

role1 = Role.objects.create(slug="foo", name="foo", parameters=["param1"])
role2 = Role.objects.create(slug="bar", name="bar")

Grant.objects.create(from_role=role2, to_role=role1, assignment={"param1": 5})

Grant.objects.get(from_role=role2, to_role=role1, assignment={"param1": 5})
# DoesNotExist: Grant matching query does not exist.
```

I came across this because I was trying to *delete* a Grant, if it exists. Is there another way to revoke Grants, or is this the method you recommend using this module?

**Comment by czue** [comment]
Hello! There hasn't been active development on this because we haven't needed to change it much since it's original implementation. @biyeun @nickpell do you know the answer to the above? @kennknowles - the original author of this, no longer maintains it, but may also have a quick answer.

**Comment by nickpell** [comment]
The ```delete``` method can be used as in the following example:
https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/accounting/management/commands/add_operations_user.py#L57

**Comment by MCGallaspy** [comment]
Thanks for the info, but note that in the example I get a Grant.DoesNotExist error when trying to get a Grant that certainly exists. Seems to be a bug when matching based on the assignment attribute.

**Comment by MCGallaspy** [comment]
FYI, I do something like this to get a Grant object with a *particular* assignment as a workaround:
```python
grants = Grant.objects.filter(
    from_role=some_role,
    to_role=some_other_role
)
grant = [g for g in grants if g.assignment == my_cool_assignment][0]
```

Whereas I would like to do this:
```python
grant = Grant.objects.get(
    from_role=some_role,
    to_role=some_other_role,
    assignment=my_cool_assignment
)
```

**Comment by millerdev** [comment]
Filtering by `assignment` is tricky since `assignment` is a `JSONField`. If you only have one parameter as in your example then you should be able to filter with serialized JSON using [this technique](http://stackoverflow.com/questions/10445176/how-to-write-a-query-to-get-find-value-in-a-json-field-in-django):
```py
import json
grant = Grant.objects.get(
    from_role=some_role,
    to_role=some_other_role,
    assignment__contains=json.dumps(my_cool_assignment)[1:-1]
)
```
If you have more than one parameter then the return value of `json.dumps` may not be deterministic, in which case you will have to filter by assignment with Python code like your first example above.
