### ISSUE TITLE
Hi there!

### ISSUE THREAD

**Issue by bnisevic** [dimagi/django-prbac#28]
Is this thing alive? Will you make it compatible with Django 1.10?

**Comment by NoahCarnahan** [comment]
Hi, this project is indeed alive, and still in use by us internally. We're currently in the process of upgrading our site to 1.9, and I believe another member of our team recently made a [PR](https://github.com/dimagi/django-prbac/pull/27) in django-prbac for 1.9 compatibility. @nickpell do you know if that was all the work necessary for 1.9 compatibility of this repo?

I don't think any of us have looked at what changes might be necessary for 1.10 use, but this is pretty light weight project, so it's possible that its already compatible! In which case we just need to update `setup.py`. If you're interested, feel free to run the tests on 1.10 and see what happens. Or, if you already know what there are breaking changes, feel free to submit a PR or let us know what they are. Thanks!

**Comment by nickpell** [comment]
@bnisevic I don't know of any existing incompatibilities with django 1.9/1.10.  I plan on ensuring its compatibility in the upcoming weeks to months.

**Comment by bnisevic** [comment]
I had errors with json-file and South. Let me try it with master branch instead of release. Maybe that will help.

**Comment by bnisevic** [comment]
Actually that doesn't work because you have clear dependency there:
django<1.9,>=1.7a

**Comment by nickpell** [comment]
With https://github.com/dimagi/django-prbac/pull/30 we now support django 1.8 through 1.10.
