### ISSUE TITLE
Hi guys

### ISSUE THREAD

**Issue by emil-jacero** [dimagi/django-prbac#31]
I was wondering if this project is still alive?

I was running through the documentation and setting it all up for my own project. I am having issues with that the documentation seems out of date and or not complete.

I am trying to add parameters like you show in your tutorial (may_view_report = Role.objects.create(name='may_view_report', parameters='report_name'). When i try this i get this error (ValueError: Invalid value 'report_name' for StringSetField)

If you guys want some help with expanding the documentation i will gladly help :)

**Comment by millerdev** [comment]
Yes, the project is still alive.

Looks like the `parameters` argument must be a set of strings. So in your example it would be
```py
may_view_report = Role.objects.create(
    name='may_view_report',
    parameters={'report_name'},
)
```
Sounds like you found at least one [incorrect example](https://github.com/dimagi/django-prbac/blob/master/docs/tutorial.rst#privileges) in the docs. Thanks for offering to help with improving that. Pull requests accepted!

**Comment by emil-jacero** [comment]
Great, I will be trying to make contributions in the near future.

On another note, what are the plans for this project in the future?
Are planning any other features?

It looks like it is complete with the features described in your name.

**Comment by millerdev** [comment]
I think it's mostly in maintenance mode for now. There are no new features planned that I know of. [Dimagi](https://www.dimagi.com/) will almost certainly continue to maintain it as long as it is used in https://github.com/dimagi/commcare-hq, and I don't see that changing anytime soon.
