### ISSUE TITLE
Docs at version 0.0.1, pypi at 0.0.4

### ISSUE THREAD

**Issue by girving** [dimagi/django-prbac#32]
It looks like the docs at https://django-prbac.readthedocs.io are older than the pypi version, at least based on the number.  Also some concepts in the code are missing from the docs, such as `UserRole`; not sure if that's related.

**Comment by millerdev** [comment]
Thanks for the bug report. The version on readthedocs is wrong, it should say 0.0.4 (the latest docs are there). https://github.com/dimagi/django-prbac/pull/34 should fix that.

> some concepts in the code are missing from the docs, such as `UserRole`; not sure if that's related.

I think that's unrelated; some things have just not been documented yet. Contributions welcome!
