### ISSUE TITLE
Django 1.11 support

### ISSUE THREAD

**Issue by girving** [dimagi/django-prbac#33]
Currently `django-prbac`'s `setup.py` requires `django<1.11`.  Is this difficult to fix?  So far there seem to be least two issues:

1. `from django.conf.urls import patterns`: Removed as of Django 1.10 (https://stackoverflow.com/questions/8074955/cannot-import-name-patterns).
2.  `from django.contrib import admin`: Throws `RemovedInDjango21Warning`.

**Comment by nickpell** [comment]
Thanks for reporting.  I'm following up with the necessary changes here: https://github.com/dimagi/django-prbac/pull/35

**Comment by girving** [comment]
Looks like this was fixed ages ago.
