### ISSUE TITLE
Is it compatible only with Django Built in User ?

### ISSUE THREAD

**Issue by ArtemBernatskyy** [dimagi/django-prbac#40]
I can't see any mentions about that in documentation.
Will it work with custom non user model ?

**Comment by millerdev** [comment]
It works with Django's built-in `User` model, as [mentioned in the documentation](http://django-prbac.readthedocs.io/en/latest/tutorial.html#users). It may be possible to make it work with a custom user model with the correct API, but I have not tried that or seen it done before.
