### ISSUE TITLE
update online documentation

### ISSUE THREAD

**Issue by moerunner** [dimagi/django-prbac#47]
hi nice project. although i managed to build the latest documentation on my own, it would be more convenient if the online version was state of the art as well - especially since you "officially" recommend it in the github readme.rst:
http://django-prbac.readthedocs.org/

**Comment by millerdev** [comment]
@moerunner thanks for reporting this. I'm looking into it.

**Comment by millerdev** [comment]
Updated, and the docs should now be updated automatically when new commits are pushed to github.

**Comment by moerunner** [comment]
thanks. just wanted to commit a py3 update, then noticed: __str__  already implemented. loooking forward to pip release now :wink:
