### ISSUE TITLE
0.0.4 breaks backcompatiblity by changing the serialization format of Grant.assignment

### ISSUE THREAD

**Issue by GertBurger** [dimagi/django-prbac#51]
Hi!

This is more of an FYI for other users since it is probably too late to fix now.

When json_field was replaced with jsonfield it changed the string json format for Grant.assignment.
This is due to ```jsonfield.JSONField``` using ',' and ':' as separators (note the missing spaces) which differ from the previous output and the default.

```'{"mymodel": 5}'``` becomes ```'{"mymodel":5}'```

This only affects queries which filter directly on ```assignment``` such as ```Grant.objects.filter(assignment=dict(mymodel=5))``` since a text comparison is performed by the DB.

Obviously such a comparison is fragile and should be used with care.

The old behaviour can be achieved with ```jsonfield.JSONField``` by setting ```dump_kwargs={}``` on the field definition.

**Comment by millerdev** [comment]
It looks like `jsonfield` was upgraded in 3bc649446d84a368dacc1dfab78f0c50dd4da611, which was part of the 0.0.4 relase: https://github.com/dimagi/django-prbac/compare/0.0.2...0.0.4

@GertBurger is there a bug in the new behavior, or does it just require a different solution than what worked before `jsonfield`?

> Obviously such a comparison is fragile and should be used with care.

I agree with this. It would be more reliable to parse the JSON and do a rich comparison. Maybe this could be achieved with one of the postgres [JSON data types](https://www.postgresql.org/docs/9.4/static/datatype-json.html)?

**Comment by GertBurger** [comment]
It just means that if you do filter by assignment (on >=0.0.4) it won't work data created pre-0.0.4

Using JSON specific data types of certain RDBMs would be an option for some but since we need to support many RDBMs we unfortunately cant.

**Comment by millerdev** [comment]
Good points, and thank you for raising the issue.

I'm going to close this since it will break backward compatibility again if we changed it back now. 0.0.4 was released almost a year ago, and the offending commit was made over two years ago.
