### ISSUE TITLE
question about UserRole model

### ISSUE THREAD

**Issue by tchenscw** [dimagi/django-prbac#52]
Hi, I noticed that there's a UserRole model to have one to one mapping between user and role. It seems quite useful but it's not being used automatically, the example did not mention it at all, and it is not even registered for admin. Is there any reason for the case? If there's some flaw in the design, I feel it may be useful to let people know and perhaps someone can contribute to fix it. 

Thanks

**Comment by millerdev** [comment]
You are correct, it is not strictly necessary to use the `UserRole` model. However, it can be useful to formalize the relationship between users and roles in your database.

Conversely, the [tutorial](https://django-prbac.readthedocs.io/en/latest/tutorial.html) uses a simple convention of creating a role for each user with its `name` and `slug` set to `user.username`. This convention works in situations where you know usernames will never collide with other role names, but may not work in more complicated scenarios where that could happen. `UserRole` is there for those more complicated scenarios. It is an optional component that you can use if you need it.

The documentation could be improved to mention `UserRole` and show how it is used. Pull requests accepted!
