### ISSUE TITLE
Update to allow django 3

### ISSUE THREAD

**Issue by OmenApps** [dimagi/django-prbac#56]
Django 3 has been out for a few months now, but setup doesn't allow usage of django-prbac with django 3.

**Comment by stgraham2000** [comment]
Is there a reason the package is excluding 3?  Was there no time to test it, or is there a specific reason?  I'm about to fork and simply update setup.py.  I'm happy to PR that back.  I'm wondering if there are known issues I'm going to hit with that change.

**Comment by millerdev** [comment]
@stgraham2000 PRs are welcome! It would be great news if you are able to use it on Django 3.
