### ISSUE TITLE
Is object-level permission control available?

### ISSUE THREAD

**Issue by devnjw** [dimagi/django-prbac#70]
Thank you for your awesome product! I have one question.

I read in the README that django-prbac provides object-level permission, but when I look at the code, I don't see the object relationship being mapped. The examples in the official documentation also don't show any examples of object-level management. How can I do this?

**Comment by gherceg** [comment]
Hey @devnjw sorry for the very late reply. I'm relatively new to this package myself, but if you're still interested in this I'm happy to try to help. Could you give an example of what you would like to do with object-level management?

**Comment by devnjw** [comment]
@gherceg Thanks for reply. I thought I saw README tells object-level permission control is available, but I can not find it now. I must have misunderstood.

**Comment by gherceg** [comment]
I believe the intention of the README section that mentions object level access control was to convey that django-prbac can be used to implement concepts like that, but isn't something that works out of the box with this package. You would be responsible for associating a `Role` object to the object that you want to control access to, and then only other `Role`s with access granted to the object's role will have access. Hope that helps clear things up.

**Comment by gherceg** [comment]
I updated the README to be more aligned with my last comment.

**Comment by devnjw** [comment]
Thanks @gherceg.
